version: '3.8'

services:

  database:
    image: postgres:15.1-alpine
    restart: always
    container_name: database

    expose:
      - "5432"
    ports:
      - "5432:5432"
    env_file:
      - .env