version: '3.8'

services:
  database:
    image: postgres:15.1-alpine
    restart: always
    container_name: database
    networks:
      - ylab_network
    expose:
      - "5432"
    ports:
      - "5432:5432"
    env_file:
      - .env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}" ]
      interval: 10s
      timeout: 30s
      retries: 5

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    networks:
      - ylab_network
    expose:
      - "6379"
    ports:
      - "6379:6379"
    env_file:
      - .env
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping | grep PONG" ]
      interval: 1s
      timeout: 3s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    restart: always
    networks:
      - ylab_network
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      database:
        condition: service_healthy
      redis:
        condition: service_healthy
networks:
  ylab_network:
    name: ylab_network
